// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_dont_give_up = "CgkI17yBusYREAIQAg"; // <GPGSID>
        public const string leaderboard_highscoreleaderboard = "CgkI17yBusYREAIQCA"; // <GPGSID>
        public const string achievement_blow_em_up = "CgkI17yBusYREAIQAA"; // <GPGSID>
        public const string achievement_hand_of_god = "CgkI17yBusYREAIQBA"; // <GPGSID>
        public const string achievement_saved_the_universe = "CgkI17yBusYREAIQBw"; // <GPGSID>
        public const string achievement_the_creator = "CgkI17yBusYREAIQBg"; // <GPGSID>
        public const string achievement_cleaning_the_galaxy = "CgkI17yBusYREAIQAw"; // <GPGSID>
        public const string achievement_eye_of_the_maker = "CgkI17yBusYREAIQBQ"; // <GPGSID>

}

